# Generated by Django 5.2.6 on 2025-09-17 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hiddenmovie',
            options={},
        ),
        migrations.RemoveField(
            model_name='hiddenmovie',
            name='date_hidden',
        ),
    ]
